texts = ["The quick brown fox", "A cat jumps over a log"]
new_text = "Fast brown fox jumps over"

water_str1 = "Koramangala 5th Block in Bengaluru is currently experiencing severe waterlogging due to accumulated rainwater making driving extremely difficult and forcing residents to wade through knee-deep water. This is a recurring issue especially during the monsoon season (June to October) impacting daily commutes public services and posing health and safety risks. Bengaluru is currently in its monsoon phase with light rain forecasted for the upcoming days suggesting the issue could persist or recur. [2 3 4 5 6 7] This reflects a broader systemic problem in Bengaluru due to inadequate and poorly maintained drainage systems clogged drains potholes unplanned urbanization and encroachment of stormwater drains. [8 9 10]\n\n**ACTIONABLE RECOMMENDATIONS=**\n*   **Immediate Safety Measures=** Avoid travel to Koramangala 5th Block if possible. If travel is unavoidable do not wade or drive through deep water as it can conceal open manholes potholes and live electrical wires. Stay indoors if you are in the affected area until water levels recede.\n*   **Alternative Routes=** Consider using the Inner Ring Road or Sarjapur Road to bypass the affected area. Monitor real-time traffic updates via navigation apps.\n*   **Emergency Contacts=**\n    *   BBMP (Bruhat Bengaluru Mahanagara Palike) Helpline= 1533 080-22660000 WhatsApp= 9480685700 (for general rain-related issues and waterlogging complaints).\n    *   BWSSB (Bangalore Water Supply and Sewerage Board) Helpline= 080-22238888 / 1916 (for overflowing manholes and sanitation).\n    *   BESCOM (Electricity Supply) Helpline= 1912 WhatsApp Sahayavani= 9483191212 9483191222 (for power cuts and electrical safety).\n    *   General Emergency Services= Police (100) Fire (101) Ambulance (102 108).\n    *   Download the Bengaluru Megha Sandesha App for real-time weather and flooding alerts.\n*   **Preventive Measures (for citizens)=** Ensure proper waste disposal to prevent drain blockages consider rainwater harvesting and keep areas around homes clean and free of stagnant water to prevent mosquito breeding.\n\n**KEY INSIGHTS=**\n*   Koramangala 5th Block is highly vulnerable to waterlogging due to existing poor drainage ongoing civic works and dense development. [8 11] Other areas prone to waterlogging include Marathahalli-Bellandur stretch Belathur-Kadugodi stretch Yemalur and Kodigehalli-Hebbal-Nagavara stretch. [8]\n*   This ongoing issue highlights a broader systemic problem in Bengaluru related to unplanned urbanization and insufficient infrastructure. [10]\n*   Even moderate rainfall can lead to significant disruption extensive traffic delays and health/safety risks. [8]\n*   BBMP and other authorities face continuous pressure to improve flood management and infrastructure. [9]"
power_str3 = "A complete blackout has been reported in Whitefield, Bengaluru, since 2:00 PM on Friday, July 25, 2025. The unscheduled power disruption is impacting homes, daily routines, work-from-home activities, and potentially medical devices reliant on electricity. Street lights are non-functional, increasing the risk of accidents; drivers should treat intersections with non-working traffic lights as four-way stops. The widespread nature of the outage suggests a significant fault or disruption in the local power distribution network, with past incidents in Whitefield involving prolonged outages due to underground cable faults. The duration of the outage is currently unknown without an official update from the power utility.\n\nImmediate safety measures include reporting the outage to BESCOM via their 24x7 helpline 1912 or the BESCOM Mithra mobile app, staying away from downed utility wires, and using flashlights or battery-operated lanterns instead of candles to prevent fire hazards. Unplug sensitive electronics to prevent damage from power surges upon restoration, and keep refrigerator/freezer doors closed to preserve food. If using generators or grills, ensure they are outdoors and at least 20 feet away from windows to prevent carbon monoxide poisoning, and never use gas stoves or ovens for heating. Residents are advised to check on elderly neighbors, those living alone, or individuals with medical conditions. For alternative solutions, use power banks or car chargers for mobile phones, have cash on hand, and ensure electric vehicles have sufficient charge to reach an external charging station. Emergency contacts include BESCOM 24x7 Helpline: 1912, BESCOM Mithra App, and BESCOM WhatsApp Numbers (General Support: 9449844640, Bengaluru East: 8277884013, Safety Issues: 9483191212, 9483191222). For future preparedness, assemble an emergency kit, ensure smoke and carbon monoxide detectors are working, and install surge protectors for sensitive electronics.\n\nCritical information is the lack of an estimated restoration time; residents should monitor official BESCOM channels for updates. Prolonged outages pose risks related to food spoilage, discomfort, and the operation of critical medical equipment. BESCOM is expected to deploy teams to identify and rectify the fault, but restoration might be delayed if it's an underground cable fault requiring specialized equipment. Continued communication with BESCOM through official channels is crucial for real-time updates."
power_str4 = "Whitefield, Bengaluru is currently experiencing an unscheduled power outage that commenced on Friday, July 25, 2025, since afternoon and is ongoing into the late evening (11:02 PM IST) with no official update or estimated time of restoration from BESCOM. This infrastructure disruption is causing significant residential and work disruptions, communication challenges due to difficulty in charging devices, and safety concerns due to darkness, potentially highlighting underlying infrastructure issues. Residents are strongly advised to immediately unplug sensitive electronics to prevent power surge damage, use safe battery-operated lights or flashlights instead of candles, conserve mobile and laptop battery life for essential communication, and check on elderly or vulnerable neighbors. For reporting the outage and staying informed, residents should utilize the BESCOM 24x7 toll-free helpline (1912), the official BESCOM Mithra app, the BESCOM website for online grievance registration, or BESCOM's WhatsApp support numbers (+91-9449844640, +91-9483191212, +91-9483191222), while also connecting with local community groups for ground-level updates. It is critical to prepare for a potentially prolonged disruption, as there is a reported lack of updates from BESCOM and past outages in the area have exceeded 36 hours; therefore, utilizing available UPS systems, inverters, or generators, keeping essential devices fully charged, storing non-perishable food and bottled water, and ensuring vehicles have sufficient fuel are recommended preparedness measures. The primary risks associated with this outage include prolonged discomfort, significant disruption to daily life and work, potential spoilage of refrigerated food, and communication difficulties, making proactive engagement through official complaint channels crucial for ensuring the outage is registered and addressed, with escalation to the Consumer Grievance Redressal Forum (CGRF) remaining an option if unresolved."
attraction_str5 = "A live concert is currently underway at Cubbon Park in Bengaluru, drawing a huge crowd enjoying live music and food stalls. This large-scale public attraction event contributes to significant foot traffic within the park and may cause increased traffic congestion in the surrounding Central Business District, despite usual weekend vehicular restrictions within the park. The event is ongoing as of Friday, July 25, 2025, and is expected to continue into the evening. For immediate safety, attendees should be mindful of their surroundings and belongings, stay hydrated, and know exit points. Public transport, particularly the Namma Metro (Cubbon Park and Vidhana Soudha stations), is highly recommended to avoid traffic and parking issues; BMTC bus services are also an option. Emergency contacts include Police (112/100), Fire (101), and Ambulance (102/108). To enhance the experience, arriving early, carrying a portable power bank, and bringing a reusable water bottle are advised. The primary risks identified are high crowd density, potential for minor injuries due to crowding, and localized traffic congestion, with the concert expected to continue for several hours, highlighting Cubbon Park's role as a vibrant community hub."
water_str2 = "A severe waterlogging event has been reported in Koramangala 5th Block, Bengaluru, following heavy rainfall overnight, causing significant disruption to traffic and residents. This area is a consistent waterlogging hotspot during monsoons due to civic infrastructure issues, including poorly designed and choked stormwater drains (K-100 and K-200) that reduce water flow. Roads are heavily flooded, leading to slow-moving traffic and recurring major traffic jams. Previous incidents have seen fallen trees, inundated homes and businesses, and submerged vehicles. Waterlogging also poses public health risks from stagnant water, increasing the potential for mosquito-borne diseases like dengue. The current situation is a result of last night's rain, and with light rain forecasted for today (Friday, July 25, 2025) and the next few days, and heavier rain expected around August 3rd and 4th, the situation could persist or worsen.\n\n**ACTIONABLE RECOMMENDATIONS:**\n*   **Immediate Safety Measures:** Avoid commuting through Koramangala 5th Block if possible. If travel is unavoidable, drive slowly and cautiously; do not attempt to drive through deep water. Stay informed by monitoring local news and traffic advisories. Pedestrians should avoid walking through flooded streets due to submerged hazards like manholes or open drains.\n*   **Alternative Routes/Solutions:** Use navigation apps for real-time traffic updates to identify less affected routes. Consider public transport or ride-sharing, but be aware that services have been impacted by severe waterlogging previously.\n*   **Emergency Contacts:** For general civic issues and waterlogging emergencies, residents can contact the Bruhat Bengaluru Mahanagara Palike (BBMP) helpline (e.g., 1533) or their disaster management cell.\n*   **Preventive Measures (for residents/businesses):** Ensure proper drainage around properties, safeguard valuables and electronics by moving them to higher ground if ground floors are prone to flooding, and report clogged drains or overflowing sewage lines to the BBMP.\n\n**KEY INSIGHTS:**\n*   **Critical Information:** Koramangala 5th Block is a notorious waterlogging zone, with such events being a common consequence of heavy rain in Bengaluru, largely attributed to inadequate urban planning and poor storm water drainage systems.\n*   **Risk Assessment:** The risk of further disruption remains high given the forecast for continued light rain over the next few days, with potential for property damage, significant travel delays, and health hazards from stagnant water.\n*   **Expected Developments:** While the ongoing Koramangala-Ejipura flyover (expected completion by March 2026) aims to ease traffic in the broader area, it is not an immediate solution for waterlogging. Civic bodies typically initiate efforts to clear blockages during such events, but long-term solutions are critically needed to address the root causes."
att_str6 = "Anubhav Singh Bassi's stand-up comedy special, 'Kisi Ko Batana Mat', is taking place in Indiranagar, Bengaluru, at an indoor performance venue resembling a theater with a stage, blue curtains, and a screen displaying the show's hashtag. The event is primarily an entertainment attraction impacting attendees with laughter and engagement, with no immediate negative consequences. A minor increase in local traffic around Indiranagar may occur during peak arrival and departure times, but no significant impact on general infrastructure is anticipated beyond normal venue operations, with shows typically lasting 1.5 hours. As a low-risk event, attendees are advised to be mindful of personal belongings and adhere to venue rules. To mitigate potential traffic and parking challenges in Indiranagar, using ride-sharing services, public transport like Namma Metro, or carpooling is recommended, and arriving early is encouraged for better seating and avoiding rushes. For on-site emergencies, venue staff should be contacted immediately, while general emergency services (Police 100, Fire 101, Ambulance 102) are available for broader needs. Preventive measures include booking tickets in advance due to high demand, checking specific venue guidelines, and familiarizing oneself with Bassi's relatable, self-deprecating, and anecdotal storytelling style, which forms the core of his new material in 'Kisi Ko Batana Mat'. While Bassi is a popular comedian with a dedicated fanbase, particularly among younger audiences, some past reviews suggest that the show's pacing might occasionally flag in later segments; however, the event is expected to proceed smoothly in a relaxed, informal atmosphere, characteristic of stand-up comedy performances."

str_list = [water_str2, attraction_str5, power_str4]

from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer("all-MiniLM-L6-v2")  # Small and fast

def is_semantically_similar(a: str, b: str, threshold: float = 0.6) -> bool:
    emb1 = model.encode(a, convert_to_tensor=True)
    emb2 = model.encode(b, convert_to_tensor=True)
    similarity = util.cos_sim(emb1, emb2)[0][0].item()
    return similarity >= threshold

def add_if_unique_semantic(strings: list[str], new_str: str, threshold: float = 0.6) -> bool:
    for existing in strings:
        if is_semantically_similar(existing, new_str, threshold):
            return False 
    strings.append(new_str)
    return True  

# Your example usage
str_list = [water_str2, attraction_str5, power_str4]

added = add_if_unique_semantic(str_list,power_str3)
print("Added:", added)
print("Updated list length:", len(str_list))


